CREATE TABLE ANIMAL (
    ANIMAL_ID INT NOT NULL,
    NAME VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci, /* βάζουμε utf8mb4 για να υποστηρίζονται οι ελληνικοί χαρακτήρες */
    SPECIES VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    BREED VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    SEX CHAR(1) NOT NULL, /* M ή F (male/female) */
    COLOR VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    DATE_OF_BIRTH DATE,
    DATE_OF_ARRIVAL DATE NOT NULL,
    IS_ADOPTABLE BOOLEAN,
    FOUND_LOCATION VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    GOT_ADOPTED BOOLEAN,
    CARETAKER INT,
    DONATOR INT,
    PRIMARY KEY (ANIMAL_ID)
);

CREATE TABLE MEDICAL_RECORD (
    HEALTH_CARD_NUMBER INT NOT NULL,
    IS_CHIPPED BOOLEAN,
    WEIGHT FLOAT,
    IS_STERILIZED BOOLEAN,
    HEALTH_ISSUES VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    ANIMAL_CODE INT NOT NULL,
    PRIMARY KEY (HEALTH_CARD_NUMBER),
    FOREIGN KEY (ANIMAL_CODE) REFERENCES ANIMAL(ANIMAL_ID)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT NOT NULL,
    FIRST_NAME VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    LAST_NAME VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    SEX CHAR(1),
    PHONE_NUMBER CHAR(10),
    DATE_OF_BIRTH DATE,
    ADDRESS VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    EMAIL_ADDRESS VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    SUPERVISOR_ID INT,
    PRIMARY KEY (EMPLOYEE_ID),
    FOREIGN KEY (SUPERVISOR_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

ALTER TABLE ANIMAL ADD FOREIGN KEY (CARETAKER) REFERENCES EMPLOYEE(EMPLOYEE_ID); /* Το βάζουμε εδώ για να έχει δημιουργηθεί ο πίνακας EMPLOYEE που κάνουμε reference */

CREATE TABLE DONATOR (
    DONATOR_ID INT NOT NULL,
    FIRST_NAME VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    LAST_NAME VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    PHONE_NUMBER CHAR(10),
    ADDRESS VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    PRIMARY KEY (DONATOR_ID)
);

ALTER TABLE ANIMAL ADD FOREIGN KEY (DONATOR) REFERENCES DONATOR(DONATOR_ID); /* Το βάζουμε εδώ για να έχει δημιουργηθεί ο πίνακας DONATOR που κάνουμε reference */

CREATE TABLE ADOPTER (
    ADOPTER_ID INT NOT NULL,
    FIRST_NAME VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    LAST_NAME VARCHAR(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    PHONE_NUMBER CHAR(10) NOT NULL,
    ADDRESS VARCHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    EMAIL_ADDRESS VARCHAR(255) NOT NULL,
    FAMILY_STATUS VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
    PRIMARY KEY (ADOPTER_ID)
);

CREATE TABLE ADOPTION_REQUEST (
    ADOPTION_ID INT NOT NULL,
    ADOPTION_STATUS VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    DATE_OF_REQUEST DATE NOT NULL,
    DATE_OF_ADOPTION DATE,
    IS_ONLINE BOOLEAN,
    WANTED_ANIMAL INT NOT NULL,
    APPLICANT INT NOT NULL,
    PRIMARY KEY (ADOPTION_ID),
    FOREIGN KEY (WANTED_ANIMAL) REFERENCES ANIMAL(ANIMAL_ID),
    FOREIGN KEY (APPLICANT) REFERENCES ADOPTER(ADOPTER_ID)
);

CREATE TABLE VACCINES_MED (
    HEALTH_CARD_NUMBER INT NOT NULL,
    VACCINE_NAME VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    PRIMARY KEY (HEALTH_CARD_NUMBER, VACCINE_NAME), /* δύο κλειδιά */
    FOREIGN KEY (HEALTH_CARD_NUMBER) REFERENCES MEDICAL_RECORD(HEALTH_CARD_NUMBER)
);
